import { useState } from "react";
import { useGlobalContext } from "../custom-hooks/context";
import Head from "next/head";

const Login = () => {
  const [data, setData] = useState(null);
  const [visibility, setVisibility] = useState(false);
  const { tokenInfo, onLogin } = useGlobalContext();

  const handleSubmit = async (e) => {
    e.preventDefault();
    const payload = await onLogin(e);
    setData(payload);
    console.log(tokenInfo, data);
  };

  return (
    <>
      <Head>
        <title>Cuit - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/c.png" />
      </Head>
      <div className="userauth-container" id="login-container">
        <h1>
          {"{"}Login to Your Account.{"}"}
        </h1>
        <div className="form-container">
          <form
            autoComplete="off"
            id="login-form"
            className="form-body"
            onSubmit={(e) => handleSubmit(e)}
          >
            <label htmlFor="username">Username: </label>
            <input type="text" name="username" id="username" required />
            <label htmlFor="password">Password: </label>
            <input
              type={visibility ? "text" : "password"}
              name="password"
              id="password"
              required
            />
            <button
              onClick={() => setVisibility(!visibility)}
              className="togglePassword"
            >
              {visibility ? "Hide Password" : "Show Password"}
            </button>
          </form>
        </div>
        <div className="submit-btn">
          <button type="submit" form="login-form">
            Login
          </button>
        </div>
        {data && data.success == false && (
          <p className="error-msg">"{data.msg}"</p>
        )}
      </div>

      <style jsx>{`
        #login-container {
          padding-top: 6.3em;
        }
      `}</style>
    </>
  );
};

export default Login;
